### ISSUE TITLE
How to add style to style pane?

### ISSUE THREAD

**Issue by lolgear** [iandol/scrivomatic#9]
Could you describe this process?

I could not understand the relationship between styles in specific format ( Multimarkdown for example ) and styles in style pane.

When I add style to format ( I dup Multimarkdown and rename it to Enhanced Multimarkdown ) at Styles section, these styles doesn't appear in styles pane.

Maybe I should set an option somewhere? ( Option to use specific format for document / text / folder? )

Thanks!

**Comment by iandol** [comment]
Hi, Styles in the editor are _not the same_ as styles in the compiler, they are separate. You can import Styles from the editor into the compiler, but they are not linked and changing the style in the editor will not change the compiler style. This is deliberate so that you can change the format using the compiler. To create styles in the compiler please see "§24.5.1 Creating a New Compile Style" section in the user manual for clear instructions.

Does this make sense?

**Comment by lolgear** [comment]
@iandol 
yes, thank you very much!
Finally, I set scrivener up as I want :)

**Comment by iandol** [comment]
You're welcome!
